include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "lib/generated/**"
    - "build/**"

  errors:
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Disable overly strict rules for template project
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false

    # Keep these enabled
    always_use_package_imports: true
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    unawaited_futures: true
